@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.unitagged;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
