# required properties
group = com.almostreliable.mods
modId = almostunified
modName = Almost Unified
modVersion = 0.0.0
minecraftVersion = 26.1-snapshot-1
neoforgeVersion = 26.1.0.0-alpha.3+snapshot-1

# replacement properties
modAuthor = Almost Reliable
modDescription = Unify all resources.
license = All Rights Reserved
githubUser = AlmostReliable
githubRepo = almostunified

# mod dependencies
#kjsVersion = 2101.7.2-build.295

# settings
almostgradle.buildconfig.package = com.almostreliable.unified
almostgradle.launchArgs.autoWorldJoin = true
almostgradle.recipeViewers.jei.runConfig = true
almostgradle.recipeViewers.jei.version = 28.2.0.9
almostgradle.recipeViewers.jei.mode = API
almostgradle.recipeViewers.jei.minecraftVersion = 26.1-snapshot-1

# gradle
org.gradle.vfs.watch = true
org.gradle.configuration-cache = true
org.gradle.parallel = true
