@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package testmod.gametest_core;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
