@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.unified.transformer;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
