@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.unitagged.transformer;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
